apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telekube.fullname" . }}
  labels:
    {{- include "telekube.labels" . | nindent 4 }}
type: Opaque
data:
  telegram-token: {{ .Values.config.telegram.token | default "" | b64enc | quote }}
